name: build
on:
  push:
    tags:
      - 'Client.Azure/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:24})
    - name: Show relese version
      run: echo $RELEASE_VERSION
    - uses: actions/checkout@master
    - name: Add NuGet.config with credentials
      env:
        GRPSOURCE: https://nuget.pkg.github.com/Totopolis/index.json
        GRPUSERNAME: Totopolis
        GRPPASS: ${{ secrets.GITHUB_TOKEN }}
      run: ./.github/workflows/AddNuGetConfigWithCredentials.sh
    - name: Debug NuGet.config
      run: cat ./NuGet.config
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100' # SDK Version to use.
    - run: dotnet pack ./prj/Monik.Client.Azure/Monik.Client.Azure.csproj -c Release -o NuGetPackages /p:Version=$RELEASE_VERSION
    - run: dotnet nuget push ./NuGetPackages/Monik.Client.Azure.$RELEASE_VERSION.nupkg